### ISSUE TITLE
Auto Messager not coming up with config files

### ISSUE THREAD

**Issue by EpicAussie** [montlikadani/AutoMessager#1]
Hello, i use http://nodecraft.com to make servers, and im using auto messager but its not coming up with config files, is that ment to happen?

**Comment by montlikadani** [comment]
@EpicAussie 
So does the plugin do not create a configuration file for adding messages?

**Comment by EpicAussie** [comment]
Yep, it's just the .jar file

**Comment by montlikadani** [comment]
@EpicAussie 
What version of Minecraft does it use? (Spigot, Bukkit and version number)

**Comment by montlikadani** [comment]
@EpicAussie 
Thank you for reporting it!
Solved and fixed: https://www.spigotmc.org/resources/automessager.43875/updates
