### ISSUE TITLE
1.14.4 - Only displays same message

### ISSUE THREAD

**Issue by Mikebbe** [montlikadani/AutoMessager#11]
The plugin works fine, and theres no issues when looking at console, however the plugin only shows the same message.

https://gyazo.com/dc2d13ef8c6d7d2c40c86549cf35fa53

[messages.txt](https://github.com/montlikadani/AutoMessager/files/3586702/messages.txt)

**Comment by montlikadani** [comment]
Reload the server will helps.

**Comment by Mikebbe** [comment]
Ah it works, thanks for quick reply :D
