### ISSUE TITLE
log

### ISSUE THREAD

**Issue by Dancbeunny98** [montlikadani/AutoMessager#12]
07:51:58 [SEVERE] at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:214)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:236)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:227)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:215)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85)
07:51:58 [SEVERE] at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108)
07:51:58 [SEVERE] at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:139)
07:51:58 [SEVERE] at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524)
07:51:58 [SEVERE] at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:518)
07:51:58 [SEVERE] at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:111)
07:51:58 [SEVERE] at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:79)
07:51:58 [SEVERE] at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71)
07:51:58 [SEVERE] at hu.montlikadani.tablist.bungee.TabList.loadFile(TabList.java:79)
07:51:58 [SEVERE] at hu.montlikadani.tablist.bungee.TabList.onEnable(TabList.java:47)
07:51:58 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
07:51:58 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:304)
07:51:58 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)
07:51:58 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
07:51:58 [SEVERE] java.lang.NullPointerException
07:51:58 [SEVERE] at hu.montlikadani.tablist.bungee.TabList.updateTab(TabList.java:150)
07:51:58 [SEVERE] at hu.montlikadani.tablist.bungee.TabList.onEnable(TabList.java:49)
07:51:58 [SEVERE] at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:247)
07:51:58 [SEVERE] at net.md_5.bungee.BungeeCord.start(BungeeCord.java:304)
07:51:58 [SEVERE] at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:43)
07:51:58 [SEVERE] at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by montlikadani** [comment]
Bad plugin, move to tablist.
