### ISSUE TITLE
Plugin is running commands, even with run-commands false

### ISSUE THREAD

**Issue by Floppi87** [montlikadani/AutoMessager#13]
### Describe your problem to what is
Plugin is running commands, even with run-commands false.

### Details
Plugin version: 1.5
Software (Spigot/Bukkit etc.. `/version`) version: Spigot 1.14.4

### Console error
No console error.

### Configuration file(s)
This is the part, if you need more, contact me.

# Run commands after sending auto messages.
run-commands:
  enable: false
  # Use %player%, %player-displayname%, %world% placeholder.
  # Use player & console arguments for first.
  commands:
  - "player: baltop"
  - "console: kit tools %player%"
  - "console: bal %player%"

### Screenshots (optional)
Send a few pictures about the problem if you can.

**Comment by montlikadani** [comment]
The latest plugin version is 2.1,so update it and put a # mark before the lines in list.
