### ISSUE TITLE
Bug with command running

### ISSUE THREAD

**Issue by Mikebbe** [montlikadani/AutoMessager#14]
I just updated to the latest version today, and since that, every time the broadcast runs, these messages get sent through aswell, even though i set the setting to false.

I just put a # in front of them so the config ignores them, but it's a bug i guess :) 

 Run commands after sending auto messages.
run-commands:
  enable: false
   Use %player%, %player-displayname%, %world% placeholder.
   Use player & console arguments for first.
  commands:
  - "player: baltop"
  - "console: kit tools %player%"
  - "console: bal %player%"

Before:
https://gyazo.com/0f8436a8fcce6837d150e59f626129cb

After:
https://gyazo.com/8d26c7099aa23db57aa69af920e65550

**Comment by montlikadani** [comment]
It's absolutely not a bug. This has been changed, due to unnecessary codes and config options. If in the list contains # before the command will be ignored, and will not sending commands.
