### ISSUE TITLE
[Bug] Messages not sent 1.15

### ISSUE THREAD

**Issue by Emivg** [montlikadani/AutoMessager#15]
### Describe your problem to what is
I have everything set up, without errors, but the messages are not sent into the server

### Details
Plugin version: 2.2
Software (Spigot/Bukkit etc.. `/version`) version: git-Paper-23 (MC: 1.15.1)

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)
Send the configuration file(s).
```
CONFIG https://pastebin.com/e6fC57Bc
ANNOUNCES https://pastebin.com/zTs3vSYw
```

### Screenshots (optional)
Send a few pictures about the problem if you can.

**Comment by montlikadani** [comment]
- Make sure the 45 minutes have passed from the clock you set.
- Make sure you are in the server connected to send a message.
- Make sure you not disabled the messages for sending to you with /am toggle command.

**Comment by Emivg** [comment]
> * Make sure the 45 minutes have passed from the clock you set.
> * Make sure you are in the server connected to send a message.
> * Make sure you not disabled the messages for sending to you with /am toggle command.

I reinstalled the plugin and config, now it seems its working!

Thank you for your time and the fast-reply
