### ISSUE TITLE
Reloading the plugin does not change message interval

### ISSUE THREAD

**Issue by Avalkiz** [montlikadani/AutoMessager#16]
### Describe your problem to what is
After changing the announcement interval in config file, reloading the plugin with /am reload does not change it's behaviour, however other changed settings seem to be reloaded properly.

Only after restarting the server the message interval is being used properly.

### Details
Plugin version:  2.2
Software (Spigot/Bukkit etc.. `/version`) version: PaperSpigot -58 (Minecraft 1.15.1)

### Console error
none

### Configuration file(s)
I guarantee it's correct, after restarting the server everything works fine.

**Comment by montlikadani** [comment]
Fixed in the latest (v2.3) version.
