### ISSUE TITLE
Displaying score in JSON

### ISSUE THREAD

**Issue by DreaDeaD666** [montlikadani/AutoMessager#17]
### Problem
Messages in JSON format do not display the player's score from the scoreboard. I checked the message code several times.
Code: https://pastebin.com/A1nQcis7

It is not yet possible to use a colon in the text.
Log: https://pastebin.com/AV7rLkMU
### Details
Plugin version: 
v2.3
Software version: 
Paper 1.15.2
Sorry for my english.

**Comment by montlikadani** [comment]
You should put in paragraph `""` the line.
Example:
```
- "json:{}"
```
