### ISSUE TITLE
Per group message not send if player has multiple group

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [montlikadani/AutoMessager#18]
### Problem

Use PermissionEx plugin to manage permission, and a player can have multiple permisson group. It seems that AutoMessager only try to test the first group that a player have,  
when AutoMessager permission group is 2nd or 3 in the sequence, player won't receive message.

If use per permission method instead, all player can receive their message,  
although it was just the same permission group with a single permission added.

### Details
Plugin version: 

2.3

Software version: 

```
[INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-acbc348 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```

Relevant plugins: 

### Console error
```
No console error or log message print.
```

### Configuration file(s)

config.yml: 

Remains default.

announces.yml:

```
messages:
permission:automessager.customMessage_Test message that work for every player
group:customMessage_This message can only send to a player have just one group instead of two at same time
```

**Comment by mhtvsSFrpHdE** [comment]
PermissionEx, permissions.yml:
```
users:
  d1ade07e-this-is-uuid:
    group:
    - randomTeleport
    - customMessage
```
As you can see, the group has two value and AutoMessager message group is the 2nd one.  
Results in no message send to this player.

If use permission, this player can receive the message.

**Comment by montlikadani** [comment]
https://github.com/montlikadani/AutoMessager/commit/76a4e30b5e48f802bd48a6d43a32a7b782ac9569
