### ISSUE TITLE
JSON messages are displayed twice

### ISSUE THREAD

**Issue by plagoutte** [montlikadani/AutoMessager#19]
### Problem

JSON message are broadcasted twice : 
- A first time, formatted
- A second time (just after), not formatted : JSON raw code

### Details
Plugin version: 2.4

Software version: PaperMC 1.14.4

Relevant plugins: 

### Console error
```
Send the console error if you have it.
```
No error logs on plugin startup
No logs on message displaying

### Configuration file(s)

config.yml: https://pastebin.com/phawBWhH
announces.yml :
```
messages:
- 'json:{"text":"Test"}'
```

### Screenshots (optional)

In the chat : 
```
Test
json:{"text":"Test"}
```

**Comment by montlikadani** [comment]
Fixed https://github.com/montlikadani/AutoMessager/commit/1be43168131f0dc2558435c01c3a96fcc4a64219
