### ISSUE TITLE
Command /am list - Bug

### ISSUE THREAD

**Issue by JDittmerCOM** [montlikadani/AutoMessager#2]
When I enter the command **/am list**, I get no feedback in the chat.
I don't get any feedback or error messages in my console either.

**Comment by montlikadani** [comment]
@JDittmerCOM 
**Thank you for reporting it!**

This error is currently being notified as already fixed. It is expected to be upgraded later.

**Comment by montlikadani** [comment]
This error has been resolved and the update is complete. https://www.spigotmc.org/resources/automessager.43875/update?update=213283
