### ISSUE TITLE
AutoMessager executes commands even when turned off

### ISSUE THREAD

**Issue by s1h4d0w** [montlikadani/AutoMessager#21]
I ran into a weird problem after updating to the most recent version of AutoMessager a few days ago. I would see the console suddenly executing `/kit tools <player>` and `/bal <player>` for 2-3 players as well as running an auto message per affected player.

It seems that AutoMessager is doing this, as they are the exact same commands that are given as example in the config. However, I have `run-commands` set to `false`.

I've removed the three commands from the config in hopes that that fixes it for now.

![image](https://user-images.githubusercontent.com/5654654/82919187-fe9e5200-9f75-11ea-8c9d-7bf4e8d7fbc8.png)

![image](https://user-images.githubusercontent.com/5654654/82919215-065df680-9f76-11ea-9440-40ca0c8dad3e.png)

**Comment by montlikadani** [comment]
Yea, you should put `#` every line of commands or remove that to do not execute commands. Example:
```
commands:
#- "player: baltop"
```

**Comment by s1h4d0w** [comment]
I just found out the issue, I didn't delete my config so I was running on version 4 of the config. Deleted it, reloaded the plugin and reconfigured. Hopefully that fixes it, but mystery solved!

The newer version doesn't have the `enable: false` anymore so it always runs commands in the config.
