### ISSUE TITLE
Duplicates based on online player count

### ISSUE THREAD

**Issue by dlnchstr** [montlikadani/AutoMessager#23]
Hello. I have this issue.

If for example 6 players are online, the plugin generates 5 duplicates of the messages in the chat.

![issue](https://user-images.githubusercontent.com/52788233/99822380-70391080-2b53-11eb-931e-3ec64385f2a9.JPG)

**Comment by montlikadani** [comment]
You using old version of automessager. Update it first time

**Comment by dlnchstr** [comment]
I'm alreday using the latest version (v2.7), but the issue is still present.
![issue](https://user-images.githubusercontent.com/52788233/99886419-a30b0380-2c3c-11eb-81cf-32fd1f62515a.JPG)
