### ISSUE TITLE
time-setup: given not working

### ISSUE THREAD

**Issue by brysondev** [montlikadani/AutoMessager#24]
### Problem

The `given` option for time-setup does not work.
### Details
Plugin version: 
v2.9
Software version: 
Paper version git-Paper-403 (MC: 1.16.4) (Implementing API version 1.16.4-R0.1-SNAPSHOT
Relevant plugins: 
None
### Configuration file(s)

config.yml: 
https://pastebin.com/JsSKwWBD
announces.yml:
```
messages:
- '[time:05:37:00]Testing Message 1'
```

**Comment by montlikadani** [comment]
```yml
# given usage: "12:50:00" - this will send a message at 12:50 with your current time zone
```

https://github.com/montlikadani/AutoMessager/wiki/File-usage#per-line-times-bukkit

**Comment by brysondev** [comment]
So, `time` in the `config.yml` requires a time in 24 hour format? 
e.g.: 
```
# Time interval for sending messages.
time: '12:00:00'

# Time settings
# Variables: ticks, second, minute, hour, custom, given
# Example: 20 ticks = 1 second; 1 second = 20 ticks; 1 minute = 60 second; 1 hour = 60 minute
# custom usage: "00:01:00" - this counts 1 minute and after it's taken then sending the message
# given usage: "12:50:00" - this will send a message at 12:50 with your current time zone
time-setup: given
```

**Comment by montlikadani** [comment]
Yes. I see that you have `[time:05:37:00]` in your messages file which will be sent at `05:37:00` (morning) in your time. Whatever the time in config.yml will be overwritten with this specified time so it will not affect each other. So the `time-setup` as well as the `time` config.yml option are not currently in use, meaning that there are no other messages in the message file than the `time:` format.

**Comment by brysondev** [comment]
Thank you for clarifying this.
