### ISSUE TITLE
Sound not working

### ISSUE THREAD

**Issue by Ipmake123** [montlikadani/AutoMessager#25]
### Problem
I tryed configuring a sound to play along to the message, but it is not working

### Details
Plugin version: latest

Software version:  Spigot 1.12.2

Relevant plugins: 

### Console error
```
No console output
```

### Configuration file(s)

config.yml: https://pastebin.com/mA9b5y0p

### Screenshots (optional)
![grafik](https://user-images.githubusercontent.com/60793254/108351978-81db9400-71e6-11eb-9dd0-15166c80a503.png)

**Comment by montlikadani** [comment]
O, I forgot to remove `enable` option check in code.
So now you have to put an `enable` above the type
```yml
sound:
  enable: true
  type: BLOCK_ANVIL_FALL, 5, 1
```

**Comment by Ipmake123** [comment]
Thanks for helping me 👍 
I love your plugin.
