### ISSUE TITLE
Hex colors causing text to be chopped off

### ISSUE THREAD

**Issue by OoLunar** [montlikadani/AutoMessager#26]
### Problem
When attempting to use a hex color codes, anything after the `#` will be chopped off. I.E:
```
- <prefix> &6We have a Discord! #7289DAhttps://discord.gg/8xWJHKBA3K
```
Will send ![2021-04-08_15 33 13](https://user-images.githubusercontent.com/46751150/114094120-8c7ae700-9881-11eb-8946-c80dfa470633.png)
If a space isn't before the `#`, like an `&`, then everything will render correctly (including the `&`):
```
- <prefix> &6We have a Discord! &#7289DAhttps://discord.gg/8xWJHKBA3K
```
![2021-04-08_15 36 12](https://user-images.githubusercontent.com/46751150/114094128-8e44aa80-9881-11eb-9659-2841ab17ec93.png)

### Details
Plugin version: v3.1 (Please add a `/am version` command)

Software version: git-Paper-584 (MC: 1.16.5) 

Relevant plugins: AutoMessager, BKCommonLib, ChestSort, Citizens, DiscordSRV, dtlTradersPlus, dynmap, Essentials, EssentialsChat, EssentialsSpawn, GSit, LocketteX, PermissionsEx, Skript, skript-gui, SmoothTimber, SuperChats, TAB, Vault, WorldEdit, WorldGuard

### Console error
N/A

### Configuration file(s)
[config.yml](https://code.forsaken-borders.net/toyuduyoti.yml)
[announces.yml](https://code.forsaken-borders.net/uqiribesen.yml)

### Screenshots (optional)
![2021-04-08_15 33 13](https://user-images.githubusercontent.com/46751150/114094120-8c7ae700-9881-11eb-8946-c80dfa470633.png)
![2021-04-08_15 36 12](https://user-images.githubusercontent.com/46751150/114094128-8e44aa80-9881-11eb-9659-2841ab17ec93.png)

**Comment by OoLunar** [comment]
Workaround is by double quoting `"` the line. Unsure if single quotes work.

**Comment by OoLunar** [comment]
Plugin automatically converts double quotes to single quotes on reload. Seems like hex messages just need to be quoted.

**Comment by MrGraycat** [comment]
> 
> 
> Plugin automatically converts double quotes to single quotes on reload. Seems like hex messages just need to be quoted.

Hello

Just looking trough all issues to see if I'm able to help with some of them anyways you are correct they need to be quoted.
You might be confused why but # with a space in front of it will convert the rest to a comment which is unreadable by the plugin and cuts it off quoting it on the other hand tells the plugin what the string is so it doesn't have to figure it out making it work properly nothing the dev can do about this as its YAML formatting.

Hope this may help :)
MrGraycat

**Comment by OoLunar** [comment]
Ah, I meant to close this issue since it was related to the YML format itself and not the plugin. Sorry!
