### ISSUE TITLE
Announce file wiping its self out

### ISSUE THREAD

**Issue by L33B0B** [montlikadani/AutoMessager#28]
### Problem

Every time the plugin/server restarts. The programmed messages get set back to default.

### Details
Plugin version: 
3.1
Software version: 
Paper 1.16.5-638
Relevant plugins: 

### Console error
```
Send the console error if you have it.
```

### Configuration file(s)

config.yml: 
Config file - https://pastebin.com/qCuQpsRu
Announce file - https://pastebin.com/EZS8a1QS

**Comment by montlikadani** [comment]
Replace `don't` -> `don''t`

**Comment by L33B0B** [comment]
You are the man! Thank you for the fast response!
