### ISSUE TITLE
Toggling automessages still not working sadly :(

### ISSUE THREAD

**Issue by Swigglez** [montlikadani/AutoMessager#4]
My players can still not toggle the automessages with (/am toggle) I believe the command is glitched because when they execute the command it says it toggles but when the next message comes it shows up for them. Please fix this issue because I love this plugin and I dont wanna have to find another one.

**Comment by montlikadani** [comment]
If a player disables automatic messages, then everyone will not see it.

**Comment by Swigglez** [comment]
Is it possible at all to fix this?

**Comment by Swigglez** [comment]
Maybe by coding it with a different approach or something, I just love this feature of your plugin and no other plugin has this. Maybe if you get it working it could make your plugin stand out from the rest more!

**Comment by Swigglez** [comment]
what im looking for is when a player types /am toggle then it toggles messages only for them when they log on and off until the toggle it back on

**Comment by montlikadani** [comment]
I'm try something do work.

### Thank you for reporting it!

**Comment by Swigglez** [comment]
hows it coming?

**Comment by montlikadani** [comment]
Not completely. I'm still testing and trying to fix it, but it works for me.
To fix it for a little while I need it.

**Comment by Swigglez** [comment]
just let me know when a patch is out, thanks for all the help man! :)

**Comment by montlikadani** [comment]
I was able to fix it after a long time. Upgrade soon...

**Comment by montlikadani** [comment]
**_This bug has been fixed in this version:_** https://www.spigotmc.org/resources/automessager.43875/update?update=229354
