### ISSUE TITLE
Command /am reload require OP even if you have automessager.reload perms.

### ISSUE THREAD

**Issue by nicku1** [montlikadani/AutoMessager#6]
I'm not sure is it bug, but it shouldn't work like that. I would like to disable OPs on my server, but this plugin require from me OP to reload it's config. Having permission should allow to reload, even without OP.

![image](https://user-images.githubusercontent.com/10550099/41521635-3311aa9a-72d3-11e8-9683-e228f7a20aff.png)

**Comment by montlikadani** [comment]
This is not a mistake. This is so straightforward that if there is a permission for the player, it should not have been given. Plus that's why the op can only access.

**Comment by nicku1** [comment]
> if there is a permission for the player, it should not have been given
but we cannot babysit administrators for that. I want to give my admin reload command and I cannot, because he needs OP. I won't give OP him, because it basically * perms. If you're thinking that's just additional secure layer, maybe give option in config to disable OPs?

**Comment by montlikadani** [comment]
I'll tell you why this is necessary.
It is necessary that when the user (or the owner) accidentally added a reload permission to one rank but would not have liked it, then if the rank has no op permission for it then the server can not `lag` because the in my code, it is solved by reload not only reloading the configuration but the entire plugin.

**Comment by nicku1** [comment]
Even so, it's still babysitting administrator, because he can "accidentally" add * to rank. Every advanced administrator wants to customize permissions on their own, that's why I'm asking for disabling OP as NECESSITY for reloading. I proposed an option in config file to disable this for people like me (who doesn't want op as a requirement for reloading plugin). It will be my problem if someone will reload plugin in my staff and lag server, not yours so please, could you implement this or find other solution for this problem?

**Comment by montlikadani** [comment]
Okay, okay, I do not want to quarrel about this. You just have to do it by rewriting the `automessages.reload: default: op` boolean false in plugin.yml. **Do this only after I've upgraded the plugin.**

**Comment by nicku1** [comment]
Thank you for understanding :) Waiting for update then!

I have a one question out of topic, will you public source code here in future? That will allow us to contribute to code ;)

**Comment by montlikadani** [comment]
I will not add the source code because many people look at it and not help, copy it and do the same for yourself. That's why I do not want it.

**Comment by montlikadani** [comment]
**_This bug has been fixed in this version:_** https://www.spigotmc.org/resources/automessager.43875/update?update=232831
