### ISSUE TITLE
Splashtext Prefix On first Automessage

### ISSUE THREAD

**Issue by ItsParsic** [montlikadani/AutoMessager#9]
Bug:
Only on first auto message a splash text image will appear in front of the message.
This will also happen with a default Config. The Splash Text contains The small letters "ZWNBSF"

spigot.1.14.1_latest_dev.jar

plugin version:
v2.0 latest

http://prntscr.com/numqne - Showing the first of three messages with the splash text.
http://prntscr.com/numr64 - all three messages start the same.

Please Help

**Comment by montlikadani** [comment]
This is not a bug just resize the chat in your client settings.
